# Generated by Django 5.1.2 on 2024-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('icon_path', models.ImageField(upload_to='icons/')),
                ('zip_path', models.FileField(blank=True, null=True, upload_to='scripts/zip/')),
                ('unzip_path', models.CharField(blank=True, max_length=255, null=True)),
                ('script', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
