# Generated by Django 4.2.16 on 2024-11-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Installer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
