# Generated by Django 4.2.20 on 2025-03-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Installer', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpurchase',
            unique_together=set(),
        ),
    ]
