# Generated by Django 4.2.16 on 2024-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installer', '0002_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='zip_path',
            field=models.FileField(blank=True, null=True, upload_to='zip/'),
        ),
    ]
